# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7k70tfbg676-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/remi_cellard/Vivado_Projects/FirstProject/FirstProject.cache/wt [current_project]
set_property parent.project_path C:/Users/remi_cellard/Vivado_Projects/FirstProject/FirstProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib C:/Users/remi_cellard/Vivado_Projects/FirstProject/and_gate_registered.vhd
catch { write_hwdef -file and_gate_registered.hwdef }
synth_design -top and_gate_registered -part xc7k70tfbg676-1
write_checkpoint and_gate_registered.dcp
catch { report_utilization -file and_gate_registered_utilization_synth.rpt -pb and_gate_registered_utilization_synth.pb }
