1:
	@echo "o"
	gcc client.c -g -o client.o
	gcc serveur.c -g -o serveur.o
	./serveur.o
	./client.o 2 + 2

2:
	rm /tmp/cle1; touch /tmp/cle1
	gcc ex2/client.c -g -o client.o
	gcc ex2/server.c -g -o server.o
	./server.o
	./client.o msglol