# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/remi_cellard/Vivado_Projects/fpga_chronometer/fpga_chronometer.cache/wt [current_project]
set_property parent.project_path C:/Users/remi_cellard/Vivado_Projects/fpga_chronometer/fpga_chronometer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/remi_cellard/Vivado_Projects/fpga_chronometer/compteur_n.vhd
  C:/Users/remi_cellard/Vivado_Projects/fpga_chronometer/hex2led.vhd
  C:/Users/remi_cellard/Vivado_Projects/fpga_chronometer/led_control.vhd
  C:/Users/remi_cellard/Vivado_Projects/fpga_chronometer/chronometer.vhd
  C:/Users/remi_cellard/Vivado_Projects/fpga_chronometer/display.vhd
}
read_xdc C:/Users/remi_cellard/Vivado_Projects/fpga_chronometer/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/remi_cellard/Vivado_Projects/fpga_chronometer/Basys3_Master.xdc]

catch { write_hwdef -file display.hwdef }
synth_design -top display -part xc7a35tcpg236-1
write_checkpoint display.dcp
catch { report_utilization -file display_utilization_synth.rpt -pb display_utilization_synth.pb }
