# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7k70tfbg676-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/remi_cellard/Vivado_Projects/Compteur_16/Compteur_16.cache/wt [current_project]
set_property parent.project_path C:/Users/remi_cellard/Vivado_Projects/Compteur_16/Compteur_16.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib C:/Users/remi_cellard/Vivado_Projects/Compteur_16/compteur_16.vhd
catch { write_hwdef -file compteur_16.hwdef }
synth_design -top compteur_16 -part xc7k70tfbg676-1
write_checkpoint compteur_16.dcp
catch { report_utilization -file compteur_16_utilization_synth.rpt -pb compteur_16_utilization_synth.pb }
