Mips ESISAR: src/memory.c File Reference
memory.c File Reference
#include "../includes/memory.h"
Functions
uint32_t get_element (memory *mem, unsigned long int address)
Get the element object.
void checks (unsigned long int address)
uint32_t gen_mask (unsigned long int *address, int octets)
void insert_element (memory *mem, unsigned long int address, uint32_t data)
uint32_t get_value (memory *mem, unsigned long int address)
Get the value object.
void insert_value (memory *mem, unsigned long int address, uint32_t data)
void delelement (memory *mem, unsigned long int address)
void aff_memory (memory *mem)
void free_memory (memory *mem)
memory * create_memory ()
Create a memory object.
int main ()
Function Documentation
aff_memory()
void aff_memory (memory * mem)
Parameters
mem
Definition at line 133 of file memory.c.
 {
     memory* elem = mem;
     while(elem->next !=NULL)
     {
         elem = elem->next;
         printf("0x%08lX=>0x%08u\n",elem->address,elem->data);
     }
 }
Referenced by main().
checks()
void checks (unsigned long int address)
Parameters
address
ERROR c'est en dehors des 4Go
ERROR c'est pas aligné
Definition at line 34 of file memory.c.
{
     if(address>max_memory){
         exit(-1);
     }else if(address%sizeof(data_type)!=0){
         exit(-2);
     }
 }
References data_type, and max_memory.
Referenced by get_value(), and insert_value().
create_memory()
memory* create_memory ()
Create a memory object.
Returns
memory*
Definition at line 163 of file memory.c.
{
     memory* elem = malloc(sizeof(memory));
     elem->next = NULL;
     elem->data = 0;
     elem->address = -1;
     return elem;
 }
Referenced by main().
delelement()
void delelement (memory * mem, unsigned long int address)
Parameters
mem
address
Definition at line 113 of file memory.c.
 {
     memory *prev_delete = mem;
     while (prev_delete->next != NULL && (prev_delete->next)->address<address)
     {
         prev_delete = prev_delete->next;
     }
     if((prev_delete->next)->address==address)
     {
         memory* mem_to_delete=prev_delete->next;
         prev_delete->next = mem_to_delete->next;
         free(mem_to_delete);
     }
 }
free_memory()
void free_memory (memory * mem)
Parameters
mem
Definition at line 147 of file memory.c.
 {
     memory* nextElem = mem;
     memory* current = mem;
     while (current!= NULL)
     {
         nextElem = current->next;
         free(current);
         current = nextElem;
     }
 }
Referenced by main().
gen_mask()
uint32_t gen_mask (unsigned long int * address, int octets)
Parameters
address
octets
Returns
data_type
Definition at line 50 of file memory.c.
{
     // 0000111100000000
     // (actual_value & (~mask)) | (value & mask)
     data_type mask=0;
     short decalage = (*address)%sizeof(data_type);//1 => 1 en trop
     unsigned long int start_address=*address-decalage;
     address=&start_address;
     for(short i=0;i<=octets;i++){
         mask|=(0xF)<<(4*(i+decalage));
     }
     return mask;
 }
References data_type.
get_element()
uint32_t get_element (memory * mem, unsigned long int address)
Get the element object.
Parameters
mem
address
Returns
data_type
Definition at line 10 of file memory.c.
 {
     bool done=false;
     memory* elem = mem;
     while(!done && elem->next !=NULL)
     {
         elem = elem->next;
         if(elem->address==address){
             done=true;
         }
     }
     data_type value;
     if(done){
         value=elem->data;
     }else{
         value=(data_type)(rand()%0xFF);
     }
     return value;
 }
References data_type.
Referenced by get_value().
get_value()
uint32_t get_value (memory * mem, unsigned long int address)
Get the value object.
Parameters
mem
address
Returns
data_type
Definition at line 92 of file memory.c.
{
     checks(address);
     return get_element(mem,address);
 }
References checks(), and get_element().
Referenced by main().
insert_element()
void insert_element (memory * mem, unsigned long int address, uint32_t data)
Parameters
mem
address
data
Definition at line 69 of file memory.c.
 {
   memory* currentAdd = mem;
   while (currentAdd->next != NULL && (currentAdd->next)->address < address) {
     currentAdd = currentAdd->next;
   }
   if (currentAdd->next!=NULL && (currentAdd->next)->address == address) {
     (currentAdd->next)->data=data;
   } else {
     memory* newElem = (memory*)malloc(sizeof(memory));
     newElem->data = data;
     newElem->address=address;
     newElem->next = currentAdd->next;
     currentAdd->next = newElem;
   }
 }
Referenced by insert_value().
insert_value()
void insert_value (memory * mem, unsigned long int address, uint32_t data)
Parameters
mem
address
data
Definition at line 103 of file memory.c.
{
     checks(address);
     insert_element(mem,address,data);
 }
References checks(), and insert_element().
Referenced by main().
main()
int main ()
Definition at line 171 of file memory.c.
           {
     memory* mem=create_memory();
     insert_value(mem,0x4,1);
     printf("0x%08x\n",get_value(mem,0x4));
     aff_memory(mem);
     free_memory(mem);
     return 0;
 }
References aff_memory(), create_memory(), free_memory(), get_value(), and insert_value().