@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Dec 13 11:18:36 +0100 2022
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto e3a34ba8b8a24e0e928367a99a0ee489 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_chrono_behav xil_defaultlib.tb_chrono -log elaborate.log"
call xelab  -wto e3a34ba8b8a24e0e928367a99a0ee489 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_chrono_behav xil_defaultlib.tb_chrono -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
